services:
  - type: web
    name: sre-backend-alpha
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_alpha:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

  - type: web
    name: sre-backend-bravo
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_bravo:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health

  - type: web
    name: sre-backend-charlie
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_charlie:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health